openapi: 3.0.1
info:
  title: K-mer Search API
  version: 1.0.0
servers:
- url: http://kmersearch-api-service/api/v1
paths:
  /build:
    post:
      operationId: build_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSamples'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Samples'
          description: OK
      tags:
      - build
      x-openapi-router-controller: openapi_server.controllers.build_controller
  /search:
    post:
      operationId: search_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchQuery'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResults'
          description: OK
        "400":
          description: Bad request (i.e. query sequence is too short)
      tags:
      - search
      x-openapi-router-controller: openapi_server.controllers.search_controller
  /variant_search:
    post:
      operationId: variant_search_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariantSearchQuery'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariantSearchResults'
          description: OK
      tags:
      - variant_search
      x-openapi-router-controller: openapi_server.controllers.variant_search_controller
components:
  schemas:
    SearchQuery:
      example:
        threshold: 0.8008281904610115
        seq: seq
      properties:
        seq:
          minLength: 31
          type: string
        threshold:
          type: number
      required:
      - seq
      - threshold
      type: object
    VariantSearchQuery:
      example:
        ref: ref
        pos: 0
        gene: gene
        alt: alt
        genbank: genbank
      properties:
        ref:
          type: string
        pos:
          type: integer
        alt:
          type: string
        gene:
          type: string
        genbank:
          type: string
      type: object
    SearchResults:
      example:
        query: query
        threshold: 0.8008281904610115
        results:
        - num_kmers: 5
          percent_kmers_found: 6.027456183070403
          num_kmers_found: 1
          sample_name: sample_name
        - num_kmers: 5
          percent_kmers_found: 6.027456183070403
          num_kmers_found: 1
          sample_name: sample_name
      properties:
        query:
          type: string
        threshold:
          type: number
        results:
          items:
            $ref: '#/components/schemas/SearchResult'
          type: array
      type: object
    SearchResult:
      example:
        num_kmers: 5
        percent_kmers_found: 6.027456183070403
        num_kmers_found: 1
        sample_name: sample_name
      properties:
        percent_kmers_found:
          type: number
        num_kmers_found:
          type: integer
        num_kmers:
          type: integer
        sample_name:
          type: string
      type: object
    VariantSearchResults:
      example:
        query: query
        results:
        - genotype: genotype
          sample_name: sample_name
        - genotype: genotype
          sample_name: sample_name
      properties:
        query:
          type: string
        results:
          items:
            $ref: '#/components/schemas/VariantSearchResult'
          type: array
      type: object
    VariantSearchResult:
      example:
        genotype: genotype
        sample_name: sample_name
      properties:
        genotype:
          type: string
        sample_name:
          type: string
      type: object
    NewSamples:
      example:
        sample_names:
        - sample_names
        - sample_names
        sample_paths:
        - sample_paths
        - sample_paths
      properties:
        sample_paths:
          items:
            type: string
          type: array
        sample_names:
          items:
            type: string
          type: array
      type: object
    Samples:
      example:
        samples:
        - name: name
        - name: name
      properties:
        samples:
          items:
            $ref: '#/components/schemas/Sample'
          type: array
      type: object
    Sample:
      example:
        name: name
      properties:
        name:
          type: string
      type: object
